# omp — oh-my-prime-agent runtime completions
# Auto-installed by `ompa completions fish` / `ompa install`. Do not hand-edit.
# Generated from `omp --help` (v18.0.4).

# --- subcommands (known) ---
complete -c omp -n "not __fish_seen_subcommand_from daemon" -a daemon -d "run the omp daemon"

# --- flags ---
complete -c omp -l model -r -d "Model to use (fuzzy match: opus, gpt-5.2, openai/gpt-5.2)"
complete -c omp -l smol -r -d "Smol/fast model (or PI_SMOL_MODEL)"
complete -c omp -l slow -r -d "Slow/reasoning model (or PI_SLOW_MODEL)"
complete -c omp -l plan -r -d "Plan model (or PI_PLAN_MODEL)"
complete -c omp -l prewalk -d "Switch to fast model at first edit/write after plan"
complete -c omp -l no-prewalk -d "Disable prewalk"
complete -c omp -l prewalk-into -r -d "Target model for prewalk (default smol)"
complete -c omp -l plan-yolo -d "Force read-only plan mode, auto-approve, then implement"
complete -c omp -l plan-yolo-into -r -d "Target model for plan-yolo (default smol)"
complete -c omp -l provider -r -d "Provider (legacy; prefer --model)"
complete -c omp -l api-key -r -d "API key (defaults to env vars)"
complete -c omp -l system-prompt -r -d "System prompt"
complete -c omp -l append-system-prompt -r -d "Append text/file to system prompt"
complete -c omp -l allow-home -d "Allow starting in ~ without temp-dir switch"
complete -c omp -l profile -r -d "Isolated profile (auth, sessions, settings, caches)"
complete -c omp -l alias -r -d "Create a shell shortcut for the profile and exit"
complete -c omp -l cwd -r -d "Directory to start in"
complete -c omp -l mode -r -a "text json rpc rpc-ui" -d "Output mode"
complete -c omp -l config -r -d "Extra config.yml-style overlay (repeatable)"
complete -c omp -l add-dir -r -d "Add workspace dir beyond cwd (repeatable)"
complete -c omp -s p -l print -d "Non-interactive: process prompt and exit"
complete -c omp -s c -l continue -d "Continue previous session"
complete -c omp -s r -l resume -r -d "Resume session (id prefix, path, or picker)"
complete -c omp -l from-claude -d "Import a Claude Code session"
complete -c omp -l from-codex -d "Import a Codex session"
complete -c omp -l session-dir -r -d "Session storage directory"
complete -c omp -l no-session -d "Ephemeral session (don't save)"
complete -c omp -l models -r -d "Comma-separated model patterns for Ctrl+P"
complete -c omp -l no-tools -d "Disable all built-in tools"
complete -c omp -l no-lsp -d "Disable LSP tools/formatting/diagnostics"
complete -c omp -l no-pty -d "Disable PTY-based interactive bash"
complete -c omp -l tools -r -d "Tools to enable (comma-separated, default all)"
complete -c omp -l thinking -r -a "off minimal low medium high xhigh max auto" -d "Thinking level"
complete -c omp -l service-tier -r -d "OpenAI service tier"
complete -c omp -l hide-thinking -d "Hide thinking blocks in TUI (display only)"
complete -c omp -l advisor -d "Enable advisor runtime (passive per-turn review)"
complete -c omp -l external-thinking -d "Private scratchpad reasoning (provider-flagged risk)"
complete -c omp -l hook -r -d "Load a hook/extension file (repeatable)"
complete -c omp -s e -l extension -r -d "Load an extension file (repeatable)"
complete -c omp -l no-extensions -d "Disable extension discovery"
complete -c omp -l no-skills -d "Disable skills discovery"
complete -c omp -l skills -r -d "Glob patterns to filter skills (e.g. git-*,docker)"
complete -c omp -l no-rules -d "Disable rules discovery"
complete -c omp -l export -r -d "Export session file to HTML and exit"
complete -c omp -l no-title -d "Disable title auto-generation"
complete -c omp -l print-thoughts -d "Include thinking blocks in print mode text"
complete -c omp -l max-time -r -d "Stop session after duration (600, 10m, 1h)"
complete -c omp -l auto-approve -d "Auto-approve all tool calls"
complete -c omp -l approval-mode -r -a "always-ask write yolo" -d "Approval mode override"
